require('prmaloney.settings')
require('prmaloney.remaps')
require('prmaloney.plugins')
require('prmaloney.plugins_settings')
require('prmaloney.autocmds')
require('prmaloney.usercmds')
-- require('prmaloney.snipe')
